development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a9aea540435b4226cfe8deb05bbae630@hammerjaw.redistogo.com:11022/
  channel_prefix: training-fc_production
